services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: bibiner
      MYSQL_DATABASE: gymjava
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/gymjava
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: bibiner
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql-data:
