services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MYSQL_ROOT_PASSWORD: bibiner
      MYSQL_DATABASE: gymjava
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backnet

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/gymjava
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: bibiner
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - backnet

  adminer:
    image: adminer
    container_name: adminer-db
    environment:
      ADMINER_DEFAULT_SERVER: mysql-db
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    networks:
      - backnet

volumes:
  mysql-data:

networks:
  backnet:
    driver: bridge
